try with modified run-airbyte-ci job

diff --git a/.github/actions/run-airbyte-ci/action.yml b/.github/actions/run-airbyte-ci/action.yml
--- a/.github/actions/run-airbyte-ci/action.yml
+++ b/.github/actions/run-airbyte-ci/action.yml
@@ -107,6 +107,16 @@ runs:
       id: get-start-timestamp
       shell: bash
       run: echo "start-timestamp=$(date +%s)" >> $GITHUB_OUTPUT
+    - name: Make symlink to airbyte-python-cdk
+      run: ln -s ./airbyte-python-cdk ../airbyte-python-cdk || echo "Failed to create symlink"
+    - name: Show local paths checked out
+      run: |
+        set -x
+        pwd
+        ls -la
+        ls -la airbyte-python-cdk || echo "No airbyte-python-cdk directory"
+        ls -laL ../airbyte-python-cdk || echo "No airbyte-python-cdk symlink"
+
     - name: Docker login
       id: docker-login
       uses: docker/login-action@v3
