test

diff --git a/.github/workflows/bump-cdk-version-and-merge-command.yml b/.github/workflows/bump-cdk-version-and-merge-command.yml
--- a/.github/workflows/bump-cdk-version-and-merge-command.yml
+++ b/.github/workflows/bump-cdk-version-and-merge-command.yml
@@ -23,76 +23,76 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Validate provided version
-        run: |
-          # Extract the provided version
-          provided_version="${{ github.event.inputs.version }}"
-          
-          # Extract the current version from version.properties
-          current_version=$(grep '^version=' airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties | cut -d'=' -f2)
-          
-          # Check if the provided version follows SemVer
-          if ! [[ "$provided_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Error: Provided version '$provided_version' is not a valid SemVer version."
-            exit 1
-          fi
-          
-          # Compare the provided version with the current version
-          if [ "$(printf '%s\n' "$current_version" "$provided_version" | sort -V | head -n1)" = "$provided_version" ] && [ "$current_version" != "$provided_version" ]; then
-            echo "Error: Provided version '$provided_version' is not greater than the current version '$current_version'."
-            exit 1
-          fi
-          
-          echo "Provided version '$provided_version' is valid and greater than the current version '$current_version'."
+#      - name: Validate provided version
+#        run: |
+#          # Extract the provided version
+#          provided_version="${{ github.event.inputs.version }}"
+#
+#          # Extract the current version from version.properties
+#          current_version=$(grep '^version=' airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties | cut -d'=' -f2)
+#
+#          # Check if the provided version follows SemVer
+#          if ! [[ "$provided_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+#            echo "Error: Provided version '$provided_version' is not a valid SemVer version."
+#            exit 1
+#          fi
+#
+#          # Compare the provided version with the current version
+#          if [ "$(printf '%s\n' "$current_version" "$provided_version" | sort -V | head -n1)" = "$provided_version" ] && [ "$current_version" != "$provided_version" ]; then
+#            echo "Error: Provided version '$provided_version' is not greater than the current version '$current_version'."
+#            exit 1
+#          fi
+#
+#          echo "Provided version '$provided_version' is valid and greater than the current version '$current_version'."
 
-      - name: Update version.properties
-        run: |
-          # Extract the provided version
-          provided_version="${{ github.event.inputs.version }}"
-          
-          # Update the version in version.properties
-          sed -i "s/^version=.*/version=$provided_version/" airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties
-          
-          echo "Updated version.properties with version '$provided_version'."
+#      - name: Update version.properties
+#        run: |
+#          # Extract the provided version
+#          provided_version="${{ github.event.inputs.version }}"
+#
+#          # Update the version in version.properties
+#          sed -i "s/^version=.*/version=$provided_version/" airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties
+#
+#          echo "Updated version.properties with version '$provided_version'."
 
-      - name: Configure Git
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
+#      - name: Configure Git
+#        run: |
+#          git config user.name "github-actions[bot]"
+#          git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Update cdkVersionRequired in build.gradle files
-        id: export-connection-modified
-        run: |
-          # Ensure the branch has the most recent updates from the master branch
-          git fetch origin master
+#      - name: Update cdkVersionRequired in build.gradle files
+#        id: export-connection-modified
+#        run: |
+#          # Ensure the branch has the most recent updates from the master branch
+#          git fetch origin master
 
-          # Get the list of modified files between the default branch and the current branch
-          modified_files=$(git diff --name-only origin/master)
+#          # Get the list of modified files between the default branch and the current branch
+#          modified_files=$(git diff --name-only origin/master)
 
-          connector_folders=$(echo "$modified_files" | \
-            grep -oP 'airbyte-integrations/connectors/\K[^/]+' | \
-            sort | \
-            uniq)
-          
-          echo "Modified connector folders: $connector_folders"
-          
-          MODIFIED_LIST_JSON=$(echo "$connector_folders" | tr ',' '\n' | jq -R . | jq -c -s .)
-          
-          echo "modified_connectors=${MODIFIED_LIST_JSON}" >> $GITHUB_OUTPUT
+#          connector_folders=$(echo "$modified_files" | \
+#            grep -oP 'airbyte-integrations/connectors/\K[^/]+' | \
+#            sort | \
+#            uniq)
+#
+#          echo "Modified connector folders: $connector_folders"
+#
+#          MODIFIED_LIST_JSON=$(echo "$connector_folders" | tr ',' '\n' | jq -R . | jq -c -s .)
+#
+#          echo "modified_connectors=${MODIFIED_LIST_JSON}" >> $GITHUB_OUTPUT
 
-          echo "$connector_folders" | while read -r folder; do
-            gradle_file="airbyte-integrations/connectors/$folder/build.gradle"
-            if [ -f "$gradle_file" ]; then
-              sed -i "s/cdkVersionRequired = '.*'/cdkVersionRequired = '${{ github.event.inputs.version }}'/" "$gradle_file"
-              sed -i "/useLocalCdk/d" "$gradle_file"
-            fi
-          done
+#          echo "$connector_folders" | while read -r folder; do
+#            gradle_file="airbyte-integrations/connectors/$folder/build.gradle"
+#            if [ -f "$gradle_file" ]; then
+#              sed -i "s/cdkVersionRequired = '.*'/cdkVersionRequired = '${{ github.event.inputs.version }}'/" "$gradle_file"
+#              sed -i "/useLocalCdk/d" "$gradle_file"
+#            fi
+#          done
 
-      - name: Commit changes
-        run: |
-          git add .
-          git commit -m "Bump the cdk version to ${{ github.event.inputs.version }}"
-          git push
+#      - name: Commit changes
+#        run: |
+#          git add .
+#          git commit -m "Bump the cdk version to ${{ github.event.inputs.version }}"
+#          git push
 
   # publish-java-cdk:
   #   needs: [bump-cdk-version]
@@ -117,6 +117,7 @@ jobs:
 
   update-changelog-and-merge:
     runs-on: ubuntu-24.04
+    needs: [bump-cdk-version]
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -124,6 +125,11 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
+      - name: Install Poetry
+        id: install_poetry
+        uses: snok/install-poetry@v1
+        with:
+          version: 1.8.5
       - name: Merge the changelog of the connectors
         working-directory: airbyte-ci/connectors/pipelines/
         env:
