Remove checklist from PR template (#25654)
* Remove checklist from PR template

* Update footer

* Update to have error message

diff --git a/.github/workflows/connector_checklist_require.yml b/.github/workflows/connector_checklist_require.yml
--- a/.github/workflows/connector_checklist_require.yml
+++ b/.github/workflows/connector_checklist_require.yml
@@ -11,6 +11,12 @@ jobs:
     name: Require Connector Merge Checklist Job
     runs-on: ubuntu-latest
     steps:
-      - uses: mheap/require-checklist-action@v2
+      - name: Ensure All Checklist Checked
+        uses: mheap/require-checklist-action@v2
         with:
-          requireChecklist: true # If this is true and there are no checklists detected, the action will fail
+          requireChecklist: false # TODO (ben) reenable in one week once pull request templates have been updated
+      - name: Send Error Message
+        if: failure()
+        run: |
+          echo "::error::All checklist items not checked. Review your PR description and comments for unchecked items."
+          exit 1
