ci: merge all summary status checks into a single check result, add logic to explicitly fail if anything fails

diff --git a/.github/workflows/connector-ci-checks.yml b/.github/workflows/connector-ci-checks.yml
--- a/.github/workflows/connector-ci-checks.yml
+++ b/.github/workflows/connector-ci-checks.yml
@@ -181,38 +181,6 @@ jobs:
           files: |
             airbyte-integrations/connectors/${{ matrix.connector }}/build/test-results/**/*.xml
 
-  jvm-connectors-test-summary:
-    name: JVM Connector Test Summary Check
-    needs: [jvm-connectors-test-matrix]
-    runs-on: ubuntu-24.04
-    steps:
-      - name: Authenticate as GitHub App
-        uses: actions/create-github-app-token@v1
-        id: get-app-token
-        if: github.event_name == 'workflow_call' && inputs.gitref != ''
-        with:
-          owner: "airbytehq"
-          repositories: "airbyte"
-          app-id: ${{ secrets.OCTAVIA_BOT_APP_ID }}
-          private-key: ${{ secrets.OCTAVIA_BOT_PRIVATE_KEY }}
-
-      # Post completion status to the PR.
-      # This is required because otherwise slash commands won't automatically
-      # update the PR checks status.
-      - name: Create Check Status
-        if: github.event_name == 'workflow_call' && inputs.gitref != ''
-        uses: LouisBrunner/checks-action@v2.0.0
-        with:
-          name: ${{ job.name }}
-          repo: "airbytehq/airbyte" # Post to the main repo, not the fork
-          sha: ${{ inputs.gitref }}
-          status: completed
-          conclusion: ${{ job.status }}
-          token: ${{ steps.get-app-token.outputs.token }}
-
-      - name: Report Test Summary
-        run: echo "✅ All JVM connector tests completed successfully (or nothing to test)."
-
   non-jvm-connectors-test-matrix:
     needs: [generate-matrix]
     runs-on: ubuntu-24.04
@@ -310,38 +278,6 @@ jobs:
           files: |
             airbyte-integrations/connectors/${{ matrix.connector }}/build/test-results/**/*.xml
 
-  non-jvm-connectors-test-summary:
-    name: Non-JVM Connector Test Summary Check
-    needs: [non-jvm-connectors-test-matrix]
-    runs-on: ubuntu-24.04
-    steps:
-      - name: Authenticate as GitHub App
-        uses: actions/create-github-app-token@v1
-        id: get-app-token
-        if: github.event_name == 'workflow_call' && inputs.gitref != ''
-        with:
-          owner: "airbytehq"
-          repositories: "airbyte"
-          app-id: ${{ secrets.OCTAVIA_BOT_APP_ID }}
-          private-key: ${{ secrets.OCTAVIA_BOT_PRIVATE_KEY }}
-
-      # Post completion status to the PR.
-      # This is required because otherwise slash commands won't automatically
-      # update the PR checks status.
-      - name: Create Check Status
-        if: github.event_name == 'workflow_call' && inputs.gitref != ''
-        uses: LouisBrunner/checks-action@v2.0.0
-        with:
-          name: ${{ job.name }}
-          repo: "airbytehq/airbyte" # Post to the main repo, not the fork
-          sha: ${{ inputs.gitref }}
-          status: completed
-          conclusion: ${{ job.status }}
-          token: ${{ steps.get-app-token.outputs.token }}
-
-      - name: Report Test Summary
-        run: echo "✅ All non-JVM connector tests completed successfully (or nothing to test)."
-
   # Lint and format checks
 
   connectors-lint-matrix:
@@ -432,14 +368,6 @@ jobs:
         # Most connectors can't pass lint checks, so this is non-blocking for now
         continue-on-error: true
 
-  lint-summary:
-    name: Connector Lint Summary Check
-    needs: [connectors-lint-matrix]
-    runs-on: ubuntu-24.04
-    steps:
-      - name: Report Lint Summary
-        run: echo "✅ All connectors lint checks completed successfully (or nothing to check)."
-
   pre-release-checks:
     if: github.event.pull_request.draft == false
     needs: [generate-matrix]
@@ -471,11 +399,51 @@ jobs:
           connector_name=${{ matrix.connector }}
           connectors-qa run --name ${connector_name%-strict-encrypt}
 
-  pre-release-checks-summary:
-    name: Pre-Release Checks Summary
-    if: github.event.pull_request.draft == false
-    needs: [pre-release-checks]
+  connector-ci-checks-summary:
+    name: Connector CI Checks Summary
+    if: always()
+    needs:
+      - jvm-connectors-test-summary
+      - non-jvm-connectors-test-summary
+      - pre-release-checks
+      - connectors-lint-matrix
     runs-on: ubuntu-24.04
     steps:
-      - name: Report Summary
-        run: echo "✅ All Pre-Release Checks completed successfully (or nothing to check)."
+      - name: Authenticate as GitHub App
+        uses: actions/create-github-app-token@v1
+        id: get-app-token
+        if: github.event_name == 'workflow_call' && inputs.gitref != ''
+        with:
+          owner: "airbytehq"
+          repositories: "airbyte"
+          app-id: ${{ secrets.OCTAVIA_BOT_APP_ID }}
+          private-key: ${{ secrets.OCTAVIA_BOT_PRIVATE_KEY }}
+
+      - name: Raise if Upstream Failure
+        if: >
+          needs.pre-release-checks.result != 'success' ||
+          needs.jvm-connectors-test-summary.result != 'success' ||
+          needs.non-jvm-connectors-test-summary.result != 'success' ||
+          needs.connectors-lint-matrix.result != 'success'
+        run: |
+          echo "❌ Some Checks failed. Marking summary as failed"
+          exit 1
+
+      - name: Report Success
+        run: |
+          # If we get here, all checks passed.
+          echo "✅ All checks passed successfully."
+
+      # Post completion status to the PR.
+      # This is required because otherwise slash commands won't automatically
+      # update the PR checks status.
+      - name: Create Check Status
+        if: always() && github.event_name == 'workflow_call' && inputs.gitref != ''
+        uses: LouisBrunner/checks-action@v2.0.0
+        with:
+          name: ${{ job.name }}
+          repo: "airbytehq/airbyte" # Post to the main repo, not the fork
+          sha: ${{ inputs.gitref }}
+          status: completed
+          conclusion: ${{ job.status }}
+          token: ${{ steps.get-app-token.outputs.token }}
