let's do this

diff --git a/.github/workflows/publish-command.yml b/.github/workflows/publish-command.yml
--- a/.github/workflows/publish-command.yml
+++ b/.github/workflows/publish-command.yml
@@ -173,189 +173,189 @@ jobs:
           middle=${stripped_connector//,/$replace}
           full="$start$middle$end"
           echo "::set-output name=connectorjson::$full"
-  # publish-image:
-  #   timeout-minutes: 240
-  #   needs:
-  #     - start-publish-image-runner-0
-  #     - preprocess-matrix
-  #   strategy:
-  #     max-parallel: 5
-  #     fail-fast: false
-  #     matrix:
-  #       connector: ${{ fromJSON(needs.preprocess-matrix.outputs.connectorjson) }}
-  #   runs-on: ${{ needs.start-publish-image-runner-0.outputs.label }}
-  #   environment: more-secrets
-  #   steps:
-  #     - name: Link comment to workflow run
-  #       if: github.event.inputs.comment-id
-  #       uses: peter-evans/create-or-update-comment@v1
-  #       with:
-  #         comment-id: ${{ github.event.inputs.comment-id }}
-  #         body: |
-  #           > :clock2: ${{matrix.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
-  #     - name: Set up Cloud SDK
-  #       uses: google-github-actions/setup-gcloud@v0
-  #       with:
-  #         service_account_key: ${{ secrets.SPEC_CACHE_SERVICE_ACCOUNT_KEY }}
-  #         export_default_credentials: true
-  #     - name: Search for valid connector name format
-  #       id: regex
-  #       uses: AsasInnab/regex-action@v1
-  #       with:
-  #         regex_pattern: "^(connectors|bases)/[a-zA-Z0-9-_]+$"
-  #         regex_flags: "i" # required to be set for this plugin
-  #         search_string: ${{ matrix.connector }}
-  #     - name: Validate input workflow format
-  #       if: steps.regex.outputs.first_match != matrix.connector
-  #       run: echo "The connector provided has an invalid format!" && exit 1
-  #     - name: Checkout Airbyte
-  #       uses: actions/checkout@v2
-  #       with:
-  #         repository: ${{ github.event.inputs.repo }}
-  #         ref: ${{ github.event.inputs.gitref }}
-  #         token: ${{ secrets.OCTAVIA_PAT }}
-  #     - name: Install Java
-  #       uses: actions/setup-java@v1
-  #       with:
-  #         java-version: "17"
-  #     - name: Install Python
-  #       uses: actions/setup-python@v2
-  #       with:
-  #         python-version: "3.9"
-  #     - name: Install Pyenv and Tox
-  #       run: |
-  #         python3 -m pip install --quiet virtualenv==16.7.9 --user
-  #         python3 -m virtualenv venv
-  #         source venv/bin/activate
-  #         pip install --quiet tox==3.24.4
-  #     - name: Install yq
-  #       if: github.event.inputs.auto-bump-version == 'true' && success()
-  #       run: |
-  #         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
-  #         sudo add-apt-repository ppa:rmescandon/yq
-  #         sudo apt update
-  #         sudo apt install yq -y
-  #     - name: Test and install CI scripts
-  #       # all CI python packages have the prefix "ci_"
-  #       run: |
-  #         source venv/bin/activate
-  #         tox -r -c ./tools/tox_ci.ini
-  #         pip install --quiet -e ./tools/ci_*
-  #     - name: Write Integration Test Credentials for ${{ matrix.connector }}
-  #       run: |
-  #         source venv/bin/activate
-  #         ci_credentials ${{ matrix.connector }}
-  #       env:
-  #         GCP_GSM_CREDENTIALS: ${{ secrets.GCP_GSM_CREDENTIALS }}
-  #     - name: Set Name and Version Environment Vars
-  #       if: startsWith(matrix.connector, 'connectors')
-  #       run: |
-  #         source tools/lib/lib.sh
-  #         DOCKERFILE=airbyte-integrations/${{ matrix.connector }}/Dockerfile
-  #         echo "IMAGE_NAME=$(echo ${{ matrix.connector }} | cut -d"/" -f2)" >> $GITHUB_ENV
-  #         echo "IMAGE_VERSION=$(_get_docker_image_version ${DOCKERFILE})" >> $GITHUB_ENV
-  #     - name: Prepare Sentry
-  #       if: startsWith(matrix.connector, 'connectors')
-  #       run: |
-  #         curl -sL https://sentry.io/get-cli/ | bash
-  #     - name: Create Sentry Release
-  #       if: startsWith(matrix.connector, 'connectors')
-  #       run: |
-  #         sentry-cli releases set-commits "${{ env.IMAGE_NAME }}@${{ env.IMAGE_VERSION }}" --auto --ignore-missing
-  #       env:
-  #         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_CONNECTOR_RELEASE_AUTH_TOKEN }}
-  #         SENTRY_ORG: airbyte-5j
-  #         SENTRY_PROJECT: airbyte-connectors
-  #     - name: Publish ${{ matrix.connector }}
-  #       run: |
-  #         echo "$SPEC_CACHE_SERVICE_ACCOUNT_KEY" > spec_cache_key_file.json && docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
-  #         ./tools/integrations/manage.sh publish airbyte-integrations/${{ matrix.connector }} ${{ github.event.inputs.run-tests }} --publish_spec_to_cache
-  #       id: publish
-  #       env:
-  #         DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
-  #         DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
-  #         # Oracle expects this variable to be set. Although usually present, this is not set by default on Github virtual runners.
-  #         TZ: UTC
-  #     - name: Finalize Sentry release
-  #       if: startsWith(matrix.connector, 'connectors')
-  #       run: |
-  #         sentry-cli releases finalize "${{ env.IMAGE_NAME }}@${{ env.IMAGE_VERSION }}"
-  #       env:
-  #         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_CONNECTOR_RELEASE_AUTH_TOKEN }}
-  #         SENTRY_ORG: airbyte-5j
-  #         SENTRY_PROJECT: airbyte-connectors
-  #     - name: Add Published Success Comment
-  #       if: github.event.inputs.comment-id && success()
-  #       uses: peter-evans/create-or-update-comment@v1
-  #       with:
-  #         comment-id: ${{ github.event.inputs.comment-id }}
-  #         body: |
-  #           > :rocket: Successfully published ${{matrix.connector}}
-  #     - name: Add Published Failure Comment
-  #       if: github.event.inputs.comment-id && !success()
-  #       uses: peter-evans/create-or-update-comment@v1
-  #       with:
-  #         comment-id: ${{ github.event.inputs.comment-id }}
-  #         body: |
-  #           > :x: Failed to publish ${{matrix.connector}}
-  #     - name: Check if connector in definitions yaml
-  #       if: github.event.inputs.auto-bump-version == 'true' && success()
-  #       run: |
-  #         connector="airbyte/${{ env.IMAGE_NAME }}"
-  #         definitionpath=./airbyte-config/init/src/main/resources/seed/
-  #         sourcecheck=$(yq e ".. | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\")" "$definitionpath"source_definitions.yaml)
-  #         destcheck=$(yq e ".. | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\")" "$definitionpath"destination_definitions.yaml)
-  #         if [[ (-z "$sourcecheck" && -z "$destcheck") ]]
-  #         then exit 1
-  #         fi
-  #     - name: Bump version in definitions yaml
-  #       if: github.event.inputs.auto-bump-version == 'true' && success()
-  #       run: |
-  #         connector="airbyte/${{ env.IMAGE_NAME }}"
-  #         definitionpath=./airbyte-config/init/src/main/resources/seed/
-  #         sourcename=$(yq e ".[] | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\") | .name" "$definitionpath"source_definitions.yaml)
-  #         destname=$(yq e ".[] | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\") | .name" "$definitionpath"destination_definitions.yaml)
-  #         if [ -z "$sourcename" ]
-  #         then yq e "(.[] | select(.name == \"$destname\").dockerImageTag)|=\"${{ env.IMAGE_VERSION }}\"" -i "$definitionpath"destination_definitions.yaml
-  #         else yq e "(.[] | select(.name == \"$sourcename\").dockerImageTag)|=\"${{ env.IMAGE_VERSION }}\"" -i "$definitionpath"source_definitions.yaml
-  #         fi
-  #     - name: Run gradle process changes
-  #       if: github.event.inputs.auto-bump-version == 'true' && success()
-  #       run: |
-  #         ./gradlew :airbyte-config:init:processResources
-  #     - name: git config
-  #       if: github.event.inputs.auto-bump-version == 'true' && success()
-  #       run: |
-  #         git config user.name 'Octavia Squidington III'
-  #         git config user.email 'octavia-squidington-iii@users.noreply.github.com'
-  #     - name: git commit and push
-  #       if: github.event.inputs.auto-bump-version == 'true' && success()
-  #       run: |
-  #         git add -u
-  #         git commit -m "auto-bump connector version"
-  #         git pull origin ${{ github.event.inputs.gitref }}
-  #         git push origin ${{ github.event.inputs.gitref }}
-  #     - name: Add Version Bump Success Comment
-  #       if: github.event.inputs.comment-id && github.event.inputs.auto-bump-version == 'true' && success()
-  #       uses: peter-evans/create-or-update-comment@v1
-  #       with:
-  #         comment-id: ${{ github.event.inputs.comment-id }}
-  #         body: |
-  #           > :rocket: Auto-bumped version for ${{matrix.connector}}
-  #     - name: Add Version Bump Failure Comment
-  #       if: github.event.inputs.comment-id && github.event.inputs.auto-bump-version == 'true' && !success()
-  #       uses: peter-evans/create-or-update-comment@v1
-  #       with:
-  #         comment-id: ${{ github.event.inputs.comment-id }}
-  #         body: |
-  #           > :x: Couldn't auto-bump version for ${{matrix.connector}}
-  #     - name: Add Final Success Comment
-  #       if: github.event.inputs.comment-id && success()
-  #       uses: peter-evans/create-or-update-comment@v1
-  #       with:
-  #         comment-id: ${{ github.event.inputs.comment-id }}
-  #         body: |
-  #           > :white_check_mark: ${{matrix.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
+  publish-image:
+    timeout-minutes: 240
+    needs:
+      - start-publish-image-runner-0
+      - preprocess-matrix
+    strategy:
+      max-parallel: 5
+      fail-fast: false
+      matrix:
+        connector: ${{ fromJSON(needs.preprocess-matrix.outputs.connectorjson) }}
+    runs-on: ${{ needs.start-publish-image-runner-0.outputs.label }}
+    environment: more-secrets
+    steps:
+      - name: Link comment to workflow run
+        if: github.event.inputs.comment-id
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          comment-id: ${{ github.event.inputs.comment-id }}
+          body: |
+            > :clock2: ${{matrix.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
+      - name: Set up Cloud SDK
+        uses: google-github-actions/setup-gcloud@v0
+        with:
+          service_account_key: ${{ secrets.SPEC_CACHE_SERVICE_ACCOUNT_KEY }}
+          export_default_credentials: true
+      - name: Search for valid connector name format
+        id: regex
+        uses: AsasInnab/regex-action@v1
+        with:
+          regex_pattern: "^(connectors|bases)/[a-zA-Z0-9-_]+$"
+          regex_flags: "i" # required to be set for this plugin
+          search_string: ${{ matrix.connector }}
+      - name: Validate input workflow format
+        if: steps.regex.outputs.first_match != matrix.connector
+        run: echo "The connector provided has an invalid format!" && exit 1
+      - name: Checkout Airbyte
+        uses: actions/checkout@v2
+        with:
+          repository: ${{ github.event.inputs.repo }}
+          ref: ${{ github.event.inputs.gitref }}
+          token: ${{ secrets.OCTAVIA_PAT }}
+      - name: Install Java
+        uses: actions/setup-java@v1
+        with:
+          java-version: "17"
+      - name: Install Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.9"
+      - name: Install Pyenv and Tox
+        run: |
+          python3 -m pip install --quiet virtualenv==16.7.9 --user
+          python3 -m virtualenv venv
+          source venv/bin/activate
+          pip install --quiet tox==3.24.4
+      - name: Install yq
+        if: github.event.inputs.auto-bump-version == 'true' && success()
+        run: |
+          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
+          sudo add-apt-repository ppa:rmescandon/yq
+          sudo apt update
+          sudo apt install yq -y
+      - name: Test and install CI scripts
+        # all CI python packages have the prefix "ci_"
+        run: |
+          source venv/bin/activate
+          tox -r -c ./tools/tox_ci.ini
+          pip install --quiet -e ./tools/ci_*
+      - name: Write Integration Test Credentials for ${{ matrix.connector }}
+        run: |
+          source venv/bin/activate
+          ci_credentials ${{ matrix.connector }}
+        env:
+          GCP_GSM_CREDENTIALS: ${{ secrets.GCP_GSM_CREDENTIALS }}
+      - name: Set Name and Version Environment Vars
+        if: startsWith(matrix.connector, 'connectors')
+        run: |
+          source tools/lib/lib.sh
+          DOCKERFILE=airbyte-integrations/${{ matrix.connector }}/Dockerfile
+          echo "IMAGE_NAME=$(echo ${{ matrix.connector }} | cut -d"/" -f2)" >> $GITHUB_ENV
+          echo "IMAGE_VERSION=$(_get_docker_image_version ${DOCKERFILE})" >> $GITHUB_ENV
+      - name: Prepare Sentry
+        if: startsWith(matrix.connector, 'connectors')
+        run: |
+          curl -sL https://sentry.io/get-cli/ | bash
+      - name: Create Sentry Release
+        if: startsWith(matrix.connector, 'connectors')
+        run: |
+          sentry-cli releases set-commits "${{ env.IMAGE_NAME }}@${{ env.IMAGE_VERSION }}" --auto --ignore-missing
+        env:
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_CONNECTOR_RELEASE_AUTH_TOKEN }}
+          SENTRY_ORG: airbyte-5j
+          SENTRY_PROJECT: airbyte-connectors
+      - name: Publish ${{ matrix.connector }}
+        run: |
+          echo "$SPEC_CACHE_SERVICE_ACCOUNT_KEY" > spec_cache_key_file.json && docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
+          ./tools/integrations/manage.sh publish airbyte-integrations/${{ matrix.connector }} ${{ github.event.inputs.run-tests }} --publish_spec_to_cache
+        id: publish
+        env:
+          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
+          # Oracle expects this variable to be set. Although usually present, this is not set by default on Github virtual runners.
+          TZ: UTC
+      - name: Finalize Sentry release
+        if: startsWith(matrix.connector, 'connectors')
+        run: |
+          sentry-cli releases finalize "${{ env.IMAGE_NAME }}@${{ env.IMAGE_VERSION }}"
+        env:
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_CONNECTOR_RELEASE_AUTH_TOKEN }}
+          SENTRY_ORG: airbyte-5j
+          SENTRY_PROJECT: airbyte-connectors
+      - name: Add Published Success Comment
+        if: github.event.inputs.comment-id && success()
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          comment-id: ${{ github.event.inputs.comment-id }}
+          body: |
+            > :rocket: Successfully published ${{matrix.connector}}
+      - name: Add Published Failure Comment
+        if: github.event.inputs.comment-id && !success()
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          comment-id: ${{ github.event.inputs.comment-id }}
+          body: |
+            > :x: Failed to publish ${{matrix.connector}}
+      - name: Check if connector in definitions yaml
+        if: github.event.inputs.auto-bump-version == 'true' && success()
+        run: |
+          connector="airbyte/${{ env.IMAGE_NAME }}"
+          definitionpath=./airbyte-config/init/src/main/resources/seed/
+          sourcecheck=$(yq e ".. | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\")" "$definitionpath"source_definitions.yaml)
+          destcheck=$(yq e ".. | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\")" "$definitionpath"destination_definitions.yaml)
+          if [[ (-z "$sourcecheck" && -z "$destcheck") ]]
+          then exit 1
+          fi
+      - name: Bump version in definitions yaml
+        if: github.event.inputs.auto-bump-version == 'true' && success()
+        run: |
+          connector="airbyte/${{ env.IMAGE_NAME }}"
+          definitionpath=./airbyte-config/init/src/main/resources/seed/
+          sourcename=$(yq e ".[] | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\") | .name" "$definitionpath"source_definitions.yaml)
+          destname=$(yq e ".[] | select(has(\"dockerRepository\")) | select(.dockerRepository == \"$connector\") | .name" "$definitionpath"destination_definitions.yaml)
+          if [ -z "$sourcename" ]
+          then yq e "(.[] | select(.name == \"$destname\").dockerImageTag)|=\"${{ env.IMAGE_VERSION }}\"" -i "$definitionpath"destination_definitions.yaml
+          else yq e "(.[] | select(.name == \"$sourcename\").dockerImageTag)|=\"${{ env.IMAGE_VERSION }}\"" -i "$definitionpath"source_definitions.yaml
+          fi
+      - name: Run gradle process changes
+        if: github.event.inputs.auto-bump-version == 'true' && success()
+        run: |
+          ./gradlew :airbyte-config:init:processResources
+      - name: git config
+        if: github.event.inputs.auto-bump-version == 'true' && success()
+        run: |
+          git config user.name 'Octavia Squidington III'
+          git config user.email 'octavia-squidington-iii@users.noreply.github.com'
+      - name: git commit and push
+        if: github.event.inputs.auto-bump-version == 'true' && success()
+        run: |
+          git add -u
+          git commit -m "auto-bump connector version"
+          git pull origin ${{ github.event.inputs.gitref }}
+          git push origin ${{ github.event.inputs.gitref }}
+      - name: Add Version Bump Success Comment
+        if: github.event.inputs.comment-id && github.event.inputs.auto-bump-version == 'true' && success()
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          comment-id: ${{ github.event.inputs.comment-id }}
+          body: |
+            > :rocket: Auto-bumped version for ${{matrix.connector}}
+      - name: Add Version Bump Failure Comment
+        if: github.event.inputs.comment-id && github.event.inputs.auto-bump-version == 'true' && !success()
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          comment-id: ${{ github.event.inputs.comment-id }}
+          body: |
+            > :x: Couldn't auto-bump version for ${{matrix.connector}}
+      - name: Add Final Success Comment
+        if: github.event.inputs.comment-id && success()
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          comment-id: ${{ github.event.inputs.comment-id }}
+          body: |
+            > :white_check_mark: ${{matrix.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
   # In case of self-hosted EC2 errors, remove this block.
   stop-publish-image-runner-0:
     if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
@@ -363,7 +363,7 @@ jobs:
     needs:
       - start-publish-image-runner-0 # required to get output from the start-runner job
       - preprocess-matrix
-      # - publish-image # required to wait when the main job is done
+      - publish-image # required to wait when the main job is done
       - find_valid_pat
     runs-on: ubuntu-latest
     steps:
@@ -390,7 +390,7 @@ jobs:
       - start-publish-image-runner-3
       - start-publish-image-runner-4
       - preprocess-matrix
-      # - publish-image # required to wait when the main job is done
+      - publish-image # required to wait when the main job is done
       - find_valid_pat
     strategy:
       fail-fast: false
